#!/bin/sh

# udevd is not started here any more. pdaemon owns it, started by pinit at
# boot, which is what makes the pgrep guard that used to be here unnecessary:
# a supervisor knows the pid of the process it forked and does not have to
# ask whether something with a matching name exists.
#
# It also means udevd runs whether or not anybody logs in. This script ran
# from init_os, which is a tty1 login profile, so on a machine sitting at the
# login prompt no device events were being processed at all.

# Now traverse /sys in order to "coldplug" devices that have
# already been discovered. Safe to repeat: re-running these only replays
# events for devices that are already there.
/bin/udevadm trigger --action=add    --type=subsystems
/bin/udevadm trigger --action=add    --type=devices
/bin/udevadm trigger --action=change --type=devices



#seatd &





