#!/bin/bash
#
# m4 - the macro processor. LFS 12.4 section 8.13.
#
# The image has had an m4 since chapter 6, cross-compiled by the chapter 5
# toolchain into lfs/usr. This is the native one that replaces it, which is
# what the book does and what nothing here had done.
#
# It matters because autoconf and libtool are m4 at run time: every configure
# script in the image is generated by it.

set -e

. "$(dirname "$(readlink -f "$0")")/common.sh"

directory=$(unpack 'm4-*.tar.xz' 'm4-1.4.20')
cd "${directory}"

export CC=gcc

./configure --prefix=/usr

make

make DESTDIR="${build_directory}" install
