#!/bin/bash
#
# udev - device node creation and management.
#
# LFS 12.4 section 8.76. udev is part of systemd; only the udev targets are
# built out of that tree, which is why the install below is a list of explicit
# copies rather than "ninja install".
#
# This is the reason glibc is in the image at all: systemd does not build
# against musl.

set -e

. "$(dirname "$(readlink -f "$0")")/common.sh"

directory=$(unpack 'systemd-*.tar.gz' 'systemd-257.8')
cd "${directory}"

export CC=gcc

# render and sgx are not groups this system has
sed -e 's/GROUP="render"/GROUP="video"/' \
    -e 's/GROUP="sgx", //'               \
    -i rules.d/50-udev-default.rules.in

# drop the one rule that needs a full systemd
sed -i '/systemd-sysctl/s/^/#/' rules.d/99-systemd.rules.in

# a standalone udev keeps its network configuration under /usr/lib/udev
sed -e '/NETWORK_DIRS/s/systemd/udev/' \
    -i src/libsystemd/sd-network/network-util.h

# Removed rather than reused. Meson stores the options a build directory was
# configured with -- c_args among them, taken from CFLAGS at that moment --
# and a second "meson setup" over an existing directory keeps them. So a
# failed build's flags outlive the change meant to fix it, which is what
# happened to the -Wno-error below: it was exported, and the build carried on
# compiling with the arguments cached before it existed. common.sh's
# meson_setup deletes the directory for this reason; this script predates it
# and sets up by hand.
rm -rf build
mkdir -p build
cd build

# The errno table systemd generates has two entries written twice, and this
# build is the reason it does.
#
# errno-to-name.h is generated by walking every E* the preprocessor can see
# and indexing an array by its value. The kernel's UAPI headers define
# EFSBADCRC as EBADMSG and EFSCORRUPTED as EUCLEAN -- aliases, same numbers --
# and build.sh stages those headers into obj/usr/include, where --sysroot
# makes them visible. A distro build never sees them: the host's /usr/include
# has neither name, because they arrive with the kernel headers rather than
# with libc. So the array initialises [74] and [117] twice and
# -Werror=override-init, which systemd turns on itself, stops the build.
#
# Both duplicates are the same string as the entry they overwrite, so the
# table is correct either way. Demoted rather than silenced: an override
# that is *not* an alias is worth seeing, and it stays a warning.
#
# Appended to CFLAGS rather than passed as -D c_args, which would replace
# what common.sh put there and take the sysroot with it.
export CFLAGS="${CFLAGS} -Wno-error=override-init"

# link-udev-shared=false keeps udev out of libsystemd-shared, which exists to
# be shared between systemd components none of which are installed here.
# logind and vconsole belong to those other components.
# Every optional dependency named, none left at auto.
#
# "auto" means meson looks, and looking finds the build machine. The library
# probe is a link test, which does not honour --sysroot, so systemd concluded
# it had the host's libpam and compiled pam-util.c against a
# security/pam_ext.h that is not in the image -- the same shape as util-linux
# finding the host's libudev, and readline before that. Whichever one is
# found first is the one that stops the build; the rest are waiting behind
# it.
#
# So the list is the answer rather than another round of one failure at a
# time. None of these is staged when udev is built, and most are not staged
# at all: this image has no PAM, no SELinux, no polkit and no cryptsetup by
# design. elfutils, xkbcommon, pcre2 and glib do arrive later for the Wayland
# stack, which is after udev and therefore still nothing udev can link.
#
# What is left enabled is what the image has by this point and udev actually
# uses: libblkid and libmount from util-linux, libacl, libcap, libkmod,
# libcrypto, and zlib, xz and zstd.
meson setup ..                  \
      --prefix=/usr             \
      --buildtype=release       \
      -D mode=release           \
      -D dev-kvm-mode=0660      \
      -D link-udev-shared=false \
      -D logind=false           \
      -D vconsole=false         \
      -D pam=disabled           \
      -D seccomp=disabled       \
      -D selinux=disabled       \
      -D apparmor=disabled      \
      -D smack=false            \
      -D polkit=disabled        \
      -D audit=disabled         \
      -D libcryptsetup=disabled \
      -D libidn2=disabled       \
      -D qrencode=disabled      \
      -D gcrypt=disabled        \
      -D gnutls=disabled        \
      -D p11kit=disabled        \
      -D libfido2=disabled      \
      -D tpm2=disabled          \
      -D elfutils=disabled      \
      -D bzip2=disabled         \
      -D lz4=disabled           \
      -D xkbcommon=disabled     \
      -D pcre2=disabled         \
      -D glib=disabled

# the helper programs udev invokes, taken from its own build definition
udev_helpers=$(grep "'name' :" ../src/udev/meson.build | \
               awk '{print $3}' | tr -d ",'" | grep -v 'udevadm')

# only the udev targets, not the rest of systemd
ninja udevadm systemd-hwdb                                           \
      $(ninja -n | grep -Eo '(src/(lib)?udev|rules.d|hwdb.d)/[^ ]*') \
      $(realpath libudev.so --relative-to .)                         \
      ${udev_helpers}

# Installed by hand because only a subset was built. Every path is prefixed
# with the staging directory; the book writes to / because it runs in a
# chroot where / already is the target.
d=${build_directory}

install -vm755 -d ${d}/usr/lib/udev/{hwdb.d,rules.d,network}
install -vm755 -d ${d}/etc/udev/{hwdb.d,rules.d,network}
install -vm755 -d ${d}/usr/{lib,share}/pkgconfig
install -vm755 -d ${d}/usr/{bin,sbin,include}

install -vm755 udevadm                       ${d}/usr/bin/
install -vm755 systemd-hwdb                  ${d}/usr/bin/udev-hwdb
ln      -svfn ../bin/udevadm                 ${d}/usr/sbin/udevd
cp      -av    libudev.so{,*[0-9]}           ${d}/usr/lib/
install -vm644 ../src/libudev/libudev.h      ${d}/usr/include/
install -vm644 src/libudev/*.pc              ${d}/usr/lib/pkgconfig/
install -vm644 src/udev/*.pc                 ${d}/usr/share/pkgconfig/
install -vm644 ../src/udev/udev.conf         ${d}/etc/udev/
install -vm644 rules.d/* ../rules.d/README   ${d}/usr/lib/udev/rules.d/
install -vm644 $(find ../rules.d/*.rules \
                 -not -name '*power-switch*') ${d}/usr/lib/udev/rules.d/
install -vm644 hwdb.d/* ../hwdb.d/{*.hwdb,README} ${d}/usr/lib/udev/hwdb.d/
install -vm755 ${udev_helpers}               ${d}/usr/lib/udev
install -vm644 ../network/99-default.link    ${d}/usr/lib/udev/network

# The book also installs man pages and the udev-lfs rules here. Man pages are
# skipped; the hwdb binary database is built on the target by "udev-hwdb
# update", since it has to be generated where the files live.
